name: irpf2020
base: core20
version: '2.2'
summary: Programa IRPF 2020
description: |
  Programa IRPF 2020.
architectures:
  - build-on: amd64
    run-on: amd64
grade: stable
confinement: strict

plugs:
  app-config-files:
    interface: personal-files
    read:
      - $HOME/.irpf
      - $HOME/.rfb
    write:
      - $HOME/.irpf
      - $HOME/.rfb

parts:
  app:
    plugin: dump
    source: IRPF2020-2.2.zip
    source-checksum: 'sha1/d06bd60125d84262d1a52c07149529b2d1837c44'
    organize:
      IRPF2020: irpf/
  java:
    plugin: dump
    source: OpenJDK11U-jre_x64_linux_hotspot_11.0.14.1_1.tar.gz
    source-checksum: 'sha1/36ea7324761aff38c0ef6d121568304390dda3a7'
    organize:
      '*': jdk11/

apps:
  irpf2020:
    command: jdk11/bin/java -Xmx256m -jar $SNAP/irpf/irpf.jar
    environment:
      JAVA_HOME: $SNAP/jdk11/
      PATH: $JAVA_HOME/bin:$PATH
    extensions: [gnome-3-38]
    plugs:
      - cups-control
      - desktop
      - desktop-legacy
      - home
      - network
      - removable-media
      - unity7
      - wayland
      - x11
      - app-config-files
