name: irpf2020
base: core20
version: '2.2'
summary: Programa IRPF 2020
description: |
  Programa IRPF 2020.

architectures:
  - build-on: amd64
    run-on: amd64
assumes:
  - command-chain
grade: stable
confinement: strict

parts:

  app-launcher:
    plugin: dump
    source: launcher

  app-package:
    plugin: dump
    source: IRPF2020-2.2.zip
    source-checksum: "sha1/d06bd60125d84262d1a52c07149529b2d1837c44"
    organize:
      IRPF2020: irpf/

  java-package:
    plugin: dump
    source: jdk-11.0.13_linux-x64_bin.tar.gz
    source-checksum: "sha1/84bdeebee4ea1a635b0cb73bfbdfaa1031548aea"
    organize:
      '*': java-jdk/

apps:

  irpf2020:
    command: run-app.sh
      - snap/command-chain/snapcraft-runner
      - snap/command-chain/desktop-launch
    extensions: [ gnome-3-38 ]
    plugs:
      - cups-control
      - desktop
      - desktop-legacy
      - home
      - network
      - removable-media
      - unity7
      - wayland
      - x11

hooks:

  configure:
    command-chain:
    - snap/command-chain/hooks-configure-desktop
    plugs:
    - desktop
